# Generated by Django 2.0.6 on 2019-12-19 09:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=600)),
                ('location', models.CharField(max_length=600)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('organization', models.CharField(blank=True, max_length=300, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.CharField(max_length=6000)),
                ('event_skill_level', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=46, null=True)),
                ('event_age_group', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Youth', '18 and Younger'), ('Young Adult', '18-20'), ('Adult', '21+'), ('All Ages', 'All Ages')], max_length=32, null=True)),
                ('programming_language', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('HTML', 'HTML'), ('C Programming Language', 'C Programming Language'), ('CSS', 'CSS'), ('Django', 'Django'), ('ReactJS', 'ReactJS'), ('React Native', 'React Native'), ('Swift', 'Swift'), ('SQL', 'SQL'), ('Ruby', 'Ruby'), ('Node.JS', 'Node.JS'), ('UI/UX', 'UI/UX')], max_length=111, null=True)),
                ('event_category', multiselectfield.db.fields.MultiSelectField(choices=[('Education', 'Education'), ('Social', 'Social'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Youth Programs', 'Youth Programs')], max_length=57)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', multiselectfield.db.fields.MultiSelectField(choices=[('Youth', '18 and Younger'), ('Young Adult', '18-20'), ('Adult', '21+'), ('All Ages', 'All Ages')], max_length=32)),
                ('skill_level', multiselectfield.db.fields.MultiSelectField(choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=46)),
                ('tech_experience', multiselectfield.db.fields.MultiSelectField(choices=[('Education', 'Education'), ('Social', 'Social'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Youth Programs', 'Youth Programs')], max_length=57)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
