# Generated by Django 2.0.6 on 2019-12-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userchoices',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='choices',
            field=models.ManyToManyField(to='CitiTechApp.UserChoices'),
        ),
        migrations.AddField(
            model_name='eventselection',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitiTechApp.UserChoices'),
        ),
        migrations.AddField(
            model_name='eventselection',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitiTechApp.Event'),
        ),
    ]
