# Generated by Django 2.0.6 on 2019-12-20 18:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0002_auto_20191220_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_age_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Youth', 'Youth'), ('Young Adult', 'Young Adult'), ('Adult', 'Adult'), ('All Ages', 'All Ages')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Youth', 'Youth'), ('Young Adult', 'Young Adult'), ('Adult', 'Adult'), ('All Ages', 'All Ages')], max_length=32),
        ),
    ]
