# Generated by Django 2.0.6 on 2019-12-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0002_auto_20191230_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
