# Generated by Django 2.0.6 on 2019-12-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0004_auto_20191220_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='choices',
        ),
    ]
