# Generated by Django 2.0.6 on 2019-12-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0005_auto_20191231_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='userOnetoOne',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
