# Generated by Django 2.0.6 on 2019-12-27 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CitiTechApp', '0005_remove_event_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='email',
            field=models.EmailField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='first_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='last_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='password',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='username',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Youth', 'Youth'), ('Young Adult', 'Young Adult'), ('Adult', 'Adult'), ('All Ages', 'All Ages')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='skill_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='tech_experience',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Education', 'Education'), ('Social', 'Social'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Youth Programs', 'Youth Programs')], max_length=57, null=True),
        ),
    ]
