# Generated by Django 2.0.6 on 2020-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0006_auto_20191231_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_site',
            field=models.URLField(default=''),
        ),
    ]
