# Generated by Django 2.0.6 on 2019-12-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0006_auto_20191227_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='groups',
            field=models.ManyToManyField(related_name='_userchoices_groups_+', to='CitiTechApp.UserChoices'),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='user_permissions',
            field=models.ManyToManyField(related_name='_userchoices_user_permissions_+', to='CitiTechApp.UserChoices'),
        ),
    ]
