# Generated by Django 2.0.6 on 2019-12-27 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0007_auto_20191227_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
