# Generated by Django 2.0.6 on 2019-12-27 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0008_userchoices_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoices',
            name='id',
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
