# Generated by Django 2.0.6 on 2019-12-28 10:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CitiTechApp', '0010_auto_20191227_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='age_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Youth', 'Youth'), ('Young Adult', 'Young Adult'), ('Adult', 'Adult'), ('All Ages', 'All Ages')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='skill_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='tech_experience',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Education', 'Education'), ('Social', 'Social'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Youth Programs', 'Youth Programs')], max_length=57, null=True),
        ),
    ]
